
version: 2

build:
  os: ubuntu-lts-latest
  apt_packages:
   - ffmpeg
  tools:
    python: "3.12"

sphinx:
  configuration: docs2/conf.py

python:
  install:
    - requirements: docs2/requirements.txt
    - requirements: docs2/sphinx_requirements.txt

formats: all
