
version: 2

build:
  os: ubuntu-lts-latest
  apt_packages:
   - ffmpeg
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
  config:
    html_static_path: ['static']

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: docs/sphinx_requirements.txt

formats: all
