[package]
name = "rusty_databallpy"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.9"
ndarray = "0.16.1"
numpy = "0.23.0"
pyo3 = { version = "0.23.3", features = ["extension-module"] }


