# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: DataBallPy Documentation
author: Alexander Oonk
logo: static/databallpy_logo.png
copyright: Copyright 2024, Alexander Oonk
exclude_patterns: [_build, Thumbs.db, .DS_Store, .env, "**.ipynb_checkpoints",]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  exclude_patterns: ["features/*models*"]
  timeout: 600

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/Alek050/databallpy  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
