name: CI/CD workflow

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup
        uses: actions/checkout@v3
      
      - name: setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install packages
        run: poetry install --with docs,developing

      - name: Linters
        run: 
          poetry run flake8 tests/ databallpy/
          poetry run isort --check-only --filter-files tests/ databallpy/
          poetry run black --check tests/ databallpy/ 

      - name: Test with pytest
        run: poetry run python -m pytest tests --pythonwarnings=once --cov-report=term-missing --cov-report=xml --cov=databallpy --cov-config=.coveragerc

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.2.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


