name: CI/CD workflow

on: [push, pull_request]

jobs:
  buld-and-test:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ">=3.8.1"

      - name: setup
        uses: actions/checkout@v2

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install packages
        run:  make deps

      - name: Linters
        run: make lint

      - name: Test with pytest
        run: make test

      - name: Build documentation
        run: make documentation
